### PR TITLE
Fix Immunefi Report #31869

### PR DESCRIPTION
**Pull request by hujw77**

### CODE REVIEW

**Comment by jiguantong** [comment]
Should we remove payable as well? https://github.com/msgport/ORMP/blob/main/src/ORMP.sol#L51

**Review by hackfisher — APPROVED** [review]

**Comment by hackfisher** [comment]
> Should we remove payable as well? https://github.com/msgport/ORMP/blob/main/src/ORMP.sol#L51

This is used for pay fees, should not be removed.

**Comment by hackfisher** [comment]
> > Should we remove payable as well? https://github.com/msgport/ORMP/blob/main/src/ORMP.sol#L51
> 
> This is used for pay fees, should not be removed.

Do you mean this instead?

https://github.com/msgport/ORMP/blob/ed758a04b24fe06db5971909a578087e564bf82d/src/ORMP.sol#L144

**Comment by jiguantong** [comment]
Also do it for tron @hujw77 https://github.com/msgport/ORMP/blob/main/tron/ORMP.f.sol#L523

**Comment by hackfisher** [comment]
@hujw77 Please also make update here:

https://github.com/msgport/ORMP/blob/ed758a04b24fe06db5971909a578087e564bf82d/tron/ORMP.f.sol#L474

**Review by hackfisher — APPROVED** [review]

**Review by xiaoch05 — APPROVED** [review]

**Pull request merged**
